include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0
enabled_layouts splits

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Tab navigation
map ctrl+page_down next_tab
map ctrl+page_up previous_tab
# Window splits
map ctrl+shift+d launch --location=hsplit --cwd=current
map ctrl+shift+r launch --location=vsplit --cwd=current

# Window navigation
map alt+up neighboring_window up
map alt+down neighboring_window down
map alt+left neighboring_window left
map alt+right neighboring_window right

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

term xterm-256color

scrollback_lines            100000